export const willayas = [
    { label: 'Adrar', value: 'adrar' },
    { label: 'Chlef', value: 'chlef' },
    { label: 'Laghouat', value: 'laghouat' },
    { label: 'Oum El Bouaghi', value: 'oum-el-bouaghi' },
    { label: 'Batna', value: 'batna' },
    { label: 'Bejaïa', value: 'bejaia' },
    { label: 'Biskra', value: 'biskra' },
    { label: 'Bechar', value: 'bechar' },
    { label: 'Blida', value: 'blida' },
    { label: 'Bouira', value: 'bouira' },
    { label: 'Tamanrasset', value: 'tamanrasset' },
    { label: 'Tebessa', value: 'tebessa' },
    { label: 'Tlemcen', value: 'tlemcen' },
    { label: 'Tiaret', value: 'tiaret' },
    { label: 'Tizi Ouzou', value: 'tizi-ouzou' },
    { label: 'Alger', value: 'alger' },
    { label: 'Djelfa', value: 'djelfa' },
    { label: 'Jijel', value: 'jijel' },
    { label: 'Setif', value: 'setif' },
    { label: 'Saïda', value: 'saida' },
    { label: 'Skikda', value: 'skikda' },
    { label: 'Sidi Bel Abbes', value: 'sidi-bel-abbes' },
    { label: 'Annaba', value: 'annaba' },
    { label: 'Guelma', value: 'guelma' },
    { label: 'Constantine', value: 'constantine' },
    { label: 'Medea', value: 'medea' },
    { label: 'Mostaganem', value: 'mostaganem' },
    { label: 'M’Sila', value: 'msila' },
    { label: 'Mascara', value: 'mascara' },
    { label: 'Ouargla', value: 'ouargla' },
    { label: 'Oran', value: 'oran' },
    { label: 'El Bayadh', value: 'el-bayadh' },
    { label: 'Illizi', value: 'illizi' },
    { label: 'Bordj Bou Arreridj', value: 'bordj-bou-arreridj' },
    { label: 'Boumerdes', value: 'boumerdes' },
    { label: 'El Tarf', value: 'el-tarf' },
    { label: 'Tindouf', value: 'tindouf' },
    { label: 'Tissemsilt', value: 'tissemsilt' },
    { label: 'El Oued', value: 'el-oued' },
    { label: 'Khenchela', value: 'khenchela' },
    { label: 'Souk Ahras', value: 'souk-ahras' },
    { label: 'Tipaza', value: 'tipaza' },
    { label: 'Mila', value: 'mila' },
    { label: 'Aïn Defla', value: 'ain-defla' },
    { label: 'Naâma', value: 'naama' },
    { label: 'Aïn Temouchent', value: 'ain-temouchent' },
    { label: 'Ghardaïa', value: 'ghardaia' },
    { label: 'Relizane', value: 'relizane' },
    { label: 'Timimoun', value: 'timimoun' },
    { label: 'Bordj Badji Mokhtar', value: 'bordj-badji-mokhtar' },
    { label: 'Ouled Djellal', value: 'ouled-djellal' },
    { label: 'Beni Abbes', value: 'beni-abbes' },
    { label: 'In Salah', value: 'in-salah' },
    { label: 'In Guezzam', value: 'in-guezzam' },
    { label: 'Touggourt', value: 'touggourt' },
    { label: 'Djanet', value: 'djanet' },
    { label: 'El M’Ghair', value: 'el-mghair' },
    { label: 'El Meniaa', value: 'el-meniaa' },
];
